int[] databaseID = new int[5];
databaseID[0] = 5456747;
databaseID[1] = 4829933;
databaseID[2] = 4721010;
databaseID[3] = 4849393;
databaseID[4] = 3848212;
int[] portID = new int[3];
portID[0] = 8800;
portID[1] = 5000;
portID[2] = 6500;
string[] databaseName = new string[5];
databaseName[0] = "DATABASE 1";
databaseName[1] = "DATABASE 2";
databaseName[2] = "DATABASE 3";
databaseName[3] = "DATABASE 4";
databaseName[4] = "DATABASE 5";
System.Console.WriteLine("General Info:");
int storageAmount = 0;
int memoryAmount = 0;
storageAmount =+ 16;
memoryAmount =+ 8;
System.Console.WriteLine($"\t{storageAmount}GB STORAGE and {memoryAmount}GB RAM allocated to {databaseName[0]} RUNNING on PORT {portID[0]}");
storageAmount =+ 16;
memoryAmount =+ 8;
System.Console.WriteLine($"\t{storageAmount}GB STORAGE and {memoryAmount}GB RAM allocated to {databaseName[1]} RUNNING on PORT {portID[1]}");